server {
    listen 80;

    # Toutes les pages et ressources du site
    # sont envoyées vers le conteneur front.
    location / {
        proxy_pass http://front:3000;
    }

    # Toutes les requêtes commençant par /api/
    # sont envoyées vers le backend Flask.
    location /api/ {
        proxy_pass http://back:5000/;
    }
}